@bearerToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ1c2VyMUBleGFtcGxlLmNvbSIsInVzZXJSb2xlIjoiVVNFUiIsImV4cCI6MTc0NzIyNDMwMywiaWF0IjoxNzQ3MjIwNzAzfQ.rn8PxI8uQA8Vok0EXdwuhUAFCNyhOfACagKAuXM89X0


### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "asdf",
  "userRole": "ADMIN",
  "nickName": "nickname"
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "test1234"
}

### todo 생성
POST http://localhost:8080/todos
Authorization: {{bearerToken}}
Content-Type: application/json

{
  "title": "title",
  "contents": "content"
}

### todos 조회, 조건 없음
GET http://localhost:8080/todos?page=1&size=10
Authorization: {{bearerToken}}

### todos 조회, 날씨 조건
GET http://localhost:8080/todos?page=1&size=10&weather=Rainy
Authorization: {{bearerToken}}

### todos 조회, 날짜 조회
GET http://localhost:8080/todos?page=1&size=10&start=2025-05-11
Authorization: {{bearerToken}}

### todos 조회, 날씨 + 날짜
GET http://localhost:8080/todos?page=1&size=10&weather=Sunny&start=2025-05-11&end=2025-05-12
Authorization: {{bearerToken}}

### todo 단건 조회
GET http://localhost:8080/todos/59
Authorization: {{bearerToken}}

### 유저 권한 변경
PATCH http://localhost:8080/admin/users/11
Content-Type: application/json
Authorization: {{bearerToken}}

{
  "role": "ADMIN"
}

### 코멘트 조회
GET http://localhost:8080/todos/102/comments
Authorization: {{bearerToken}}

### todo 조건 조회
GET http://localhost:8080/todos/search?page=1&size=10
Authorization: {{bearerToken}}

### todo 조건 조회
GET http://localhost:8080/todos/search?page=1&size=10&range=3
Authorization: {{bearerToken}}

### todo 조건 조회
GET http://localhost:8080/todos/search?page=1&size=10&range=3&title=User6
Authorization: {{bearerToken}}

### todo 조건 조회
GET http://localhost:8080/todos/search?page=1&size=10&range=3&nickName=User9&title=User6
Authorization: {{bearerToken}}