@bearerToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IlVTRVIiLCJleHAiOjE3NDcwMzI4NDcsImlhdCI6MTc0NzAyOTI0N30.J4jrIkBSSpyIyMzc501Zp2n0i0W4_XxKormY76QCtOo


### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "asdf",
  "userRole": "USER",
  "nickName": "nickname"
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "asdf"
}

### todo 생성
POST http://localhost:8080/todos
Authorization: {{bearerToken}}
Content-Type: application/json

{
  "title": "title",
  "contents": "content"
}

### todos 조회, 조건 없음
GET http://localhost:8080/todos?page=1&size=10

### todos 조회, 날씨 조건
GET http://localhost:8080/todos?page=1&size=10&weather=Rainy

### todos 조회, 날짜 조회
GET http://localhost:8080/todos?page=1&size=10&start=2025-05-11

### todos 조회, 날씨 + 날짜
GET http://localhost:8080/todos?page=1&size=10&weather=Sunny&start=2025-05-11&end=2025-05-12

### todo 단건 조회
GET http://localhost:8080/todos/202

### 유저 권한 변경
PATCH http://localhost:8080/admin/users/11
Content-Type: application/json

{
  "role": "ADMIN"
}
